### ISSUE TITLE
No support for multiline statements

### ISSUE THREAD

**Issue by dennis-koster** [czim/with-blade-directive#1]
`Incorrect @with directive parameters` is thrown when the statement within the directive is spread across multiple lines.

**Comment by czim** [comment]
This is not an issue with this directive specifically. Blade directives cannot span multiple lines (yet). Otwell has indicated that he won't be doing this himself, so unless a PR is created for this, it won't happen.

In any case, I've prepared this package to support multiline arguments, just in case it ever happens.
